pipeline {
    agent {
        kubernetes {
          label 'kubepod'
          defaultContainer 'gcloud'
        }
    }
    environment {
           def projects_params = "${projects_params}"


    }
    parameters {

        string( name: 'projects_params',
                description: 'json string',
                defaultValue: '{"foo":"bar","cat":"fish"}'
        )
    }
    stages {
        stage ('Test received params') {
                        steps {
                            sh '''
                            echo \"$projects_params\"
                            '''
                        }
                    }
        stage('Setup Terraform & Dependencies') {
             steps {
                 container('gcloud') {
                     sh '''
                         apt-get -y install jq wget unzip
                         wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_linux_amd64.zip
                         unzip -q /tmp/terraform.zip -d /tmp
                         chmod +x /tmp/terraform
                         mv /tmp/terraform /usr/local/bin
                         rm /tmp/terraform.zip
                         terraform --version
                        '''
                 }
             }

         }
         stage('Initialise') {
                     steps {
                         sh '''
                             echo Setup projects_params
                             echo \"$projects_params\" | jq "." > terraform.auto.tfvars.json
                             pwd
                             ls
                             pwd
                             cat ./terraform.auto.tfvars.json
                             echo Activate service account
                             gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
                         '''
                    }
         }
    }
}
