pipeline {
    agent {
        kubernetes {
          label 'kubepod'
          defaultContainer 'gcloud'
        }
    }
    environment {
           def projects_params = "${projects_params}"
           def CICD_PROJECT_ID = "${CICD_PROJECT_ID}"


    }
    parameters {

        string( name: 'projects_params',
                description: 'json string',
                defaultValue: '{"abc":"123","cat":"fish"}'
        )
    }
    stages {
        stage ('Test received params') {
                        steps {
                            sh '''
                            echo \"$projects_params\"
                            '''
                        }
                    }
        stage('Setup Terraform & Dependencies') {
             steps {
                 container('gcloud') {
                     sh '''
                         apt-get -y install jq wget unzip
                         wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_linux_amd64.zip
                         unzip -q /tmp/terraform.zip -d /tmp
                         chmod +x /tmp/terraform
                         mv /tmp/terraform /usr/local/bin
                         rm /tmp/terraform.zip
                         terraform --version
                        '''
                 }
             }

         }
         stage('Initialise') {
             steps {
                 sh '''
                     echo "Creating terraform auto file"
                     echo \"$projects_params\" | jq "." > terraform.auto.tfvars.json

                     echo "Exporting cloud build project id"
                     export CLOUD_BUILD_PROJECT_ID=$CICD_PROJECT_ID
                     echo $CICD_PROJECT_ID

                     echo "Activating service account"
                     gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
                 '''
            }
         }
         stage('Make Project') {
              steps {
                  sh '''
                      make projects
                  '''
             }
        }
    }
}
